// Code generated by gobind. DO NOT EDIT.

// Java class tsnetbind.Server is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/inscope-labs/skylarstudio/tools/tsnet-android-bind/tsnetbind
package tsnetbind;

import go.Seq;

/**
 * Server wraps a tsnet.Server with a gobind-compatible surface.
 */
public final class Server implements Seq.Proxy {
	static { Tsnetbind.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	/**
	 * NewServer constructs a Server. Nothing is started yet — call Start.
	
	Named NewServer, not New: gobind&#39;s constructor recognition matches
	`func NewT(...) *T` for type T specifically (confirmed against gomobile&#39;s
	bind generator source/tests) — a bare `New` doesn&#39;t match that pattern
	and would also collide with `new`, a reserved word in Java.
	
	  - hostname: the name this node presents on the tailnet.
	  - authKey: short-lived Tailscale auth key (Phase 5/6 Issuer output).
	  - stateDir: local directory for tsnet&#39;s persistent state. Must be a
	    location the Android process can actually write to (e.g. the app&#39;s
	    filesDir) — not decided/wired in from the Kotlin side yet.
	 */
	public Server(String hostname, String authKey, String stateDir) {
		this.refnum = __NewServer(hostname, authKey, stateDir);
		Seq.trackGoRef(refnum, this);
	}
	
	private static native int __NewServer(String hostname, String authKey, String stateDir);
	
	Server(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	/**
	 * Start brings the node up and blocks until it has joined the tailnet or
	failed. Returns the node&#39;s assigned Tailscale IPv4 address as a string
	on success — TsnetMeshNode.kt&#39;s Kotlin side maps this directly into
	MeshNodeState.Running&#39;s tailscaleIp field.
	
	Deliberately returns (string, error) rather than the full status object:
	keeping the gobind surface minimal and easy to keep binding-compatible
	as tsnet&#39;s own API evolves. Expand this only if a later phase needs more
	of the status than just the IP.
	 */
	public native String start() throws Exception;
	/**
	 * Stop tears the node down and releases its tailnet session.
	 */
	public native void stop() throws Exception;
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof Server)) {
		    return false;
		}
		Server that = (Server)o;
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("Server").append("{");
		return b.append("}").toString();
	}
}

