// Code generated by gobind. DO NOT EDIT.

// Java class tsnetbind.Tsnetbind is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/inscope-labs/skylarstudio/tools/tsnet-android-bind/tsnetbind
package tsnetbind;

import go.Seq;

public abstract class Tsnetbind {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private Tsnetbind() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	
	
	/**
	 * NewServer constructs a Server. Nothing is started yet — call Start.
	
	Named NewServer, not New: gobind&#39;s constructor recognition matches
	`func NewT(...) *T` for type T specifically (confirmed against gomobile&#39;s
	bind generator source/tests) — a bare `New` doesn&#39;t match that pattern
	and would also collide with `new`, a reserved word in Java.
	
	  - hostname: the name this node presents on the tailnet.
	  - authKey: short-lived Tailscale auth key (Phase 5/6 Issuer output).
	  - stateDir: local directory for tsnet&#39;s persistent state. Must be a
	    location the Android process can actually write to (e.g. the app&#39;s
	    filesDir) — not decided/wired in from the Kotlin side yet.
	 */
	public static native Server newServer(String hostname, String authKey, String stateDir);
}
